"""Initial schema

Revision ID: 7e2c7ac1e341
Revises:
Create Date: 2026-06-06 09:23:55.550621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2c7ac1e341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('reachability', sa.String(length=30), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('redirect_chain', sa.JSON(), nullable=False),
    sa.Column('features_summary', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_url_hash'), ['url_hash'], unique=False)

    op.create_table('blacklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('users')
    op.drop_table('request_logs')
    op.drop_table('reports')
    op.drop_table('blacklists')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_url_hash'))
        batch_op.drop_index(batch_op.f('ix_analyses_label'))
        batch_op.drop_index(batch_op.f('ix_analyses_domain'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
